# Generated by Django 3.1.2 on 2023-05-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carrito_cliente_compras'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compras',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
