# Generated by Django 3.1.2 on 2023-05-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230509_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='cliente',
            field=models.CharField(max_length=50),
        ),
    ]
