# Generated by Django 3.1.2 on 2023-05-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230518_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
