# Generated by Django 3.1.2 on 2023-05-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230518_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='usuario',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
