# Generated by Django 3.1.2 on 2023-05-21 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_suscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoSuscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='precio',
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='suscripcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tiposuscripcion'),
            preserve_default=False,
        ),
    ]
