# Generated by Django 3.1.2 on 2023-05-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230521_0023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compras',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='compras',
            name='producto',
        ),
        migrations.AddField(
            model_name='compras',
            name='contacto',
            field=models.CharField(default='ninguna', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compras',
            name='direccion',
            field=models.CharField(default='sin telefono', max_length=50),
            preserve_default=False,
        ),
    ]
