# Generated by Django 3.1.2 on 2023-06-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_compras_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
    ]
