# Generated by Django 3.1.2 on 2023-06-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='descuento',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='subtotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
