# Generated by Django 3.1.2 on 2023-06-29 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_suscripcion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='codigo',
            field=models.CharField(default='dsadsa', max_length=20),
            preserve_default=False,
        ),
    ]
