# Generated by Django 3.1.2 on 2023-06-29 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_carrito_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='codigo',
        ),
    ]
